### PR TITLE
Adding Rogier, other NPC quest updates

### PR DESCRIPTION
**Pull request by wdya**
- I added a full write-up of Rogier's questline.
- I added more information to Roderika, Hewg, and Varre.
- I added a link to the name of every NPC (only Roderika's had one before).
- I fixed a couple typos on the NPC page just from skimming it.

### CODE REVIEW

**Comment by azy2** [comment]
Keep in mind we keep track of checkboxes based on the first number in the list so if you change the contents of a line but leave the number of the same people will come back to the site and see it checked despite potentially not having done the step.

**Comment by wdya** [comment]
> Keep in mind we keep track of checkboxes based on the first number in the list so if you change the contents of a line but leave the number the same people will come back to the site and see it checked despite potentially not having done the step.

Fair, I wasn't aware the project was that public already. With the changes I made with Hewg for example, should I have numbered the steps something like 1 (mostly unchanged), 4, 5, 3 (maps onto old #3), rather than 1 2 3 4?

**Comment by azy2** [comment]
Yeah that looks good to me.

**Comment by wdya** [comment]
I have made those fixes and added three new NPC questlines as well.

**Comment by azy2** [comment]
This looks fantastic. Thanks so much!

**Pull request merged**
